### ISSUE TITLE
height and width not working

### ISSUE THREAD

**Issue by markgrujic** [JohnCoene/tippy#1]
Hi,
Thanks for the work on this package, it's really great!

I'm trying to set the height and width of the tooltip so that it encompasses all the content. The width of the tooltip seems to be determined based off the height of the tooltip that fits the content at "100%"

```r
library(shiny)
library(tippy)
shinyApp(
  ui = fluidPage(
    tippy(text = "<b>Text</b>",
          allowHTML = T,
          interactive = T,
          tooltip = paste(img(src="http://tippy.john-coene.com/logo.png",
                              height="150%", width = "150%")),
          placement = "right",
          arrow = T,
          height = '600px', width = '600px' # this doesn't appear to do anything
    )
  ),
  server = function(input, output) {}
)
```

Running that snippet, you can see that the tooltip height is good but the width is short. Changing the height and width arguments inside the img() function to 100% fix the out-of-tooltip issue, but the tooltip is a fixed size and the image is forced to be that size.

Is there a way to change the size of the tooltip? The [size](https://atomiks.github.io/tippyjs/#size-option) argument doesn't seem to work either, however it does something:
![tippysize](https://user-images.githubusercontent.com/39284163/49195605-df078700-f3db-11e8-90e5-d6b354d01a00.gif)

Cheers

**Comment by JohnCoene** [comment]
Thanks for reporting that.

I just updated the package to version `3.2.0`. The arguments `width` and `height` never did anything, I should have removed them earlier on. The issue comes from changing the `width` of the original image. In the new version at least, the code below works.

```r
library(shiny)
library(tippy)

shinyApp(
  ui = fluidPage(
    tippy(text = "<b>Text</b>",
          allowHTML = TRUE,
          interactive = TRUE,
          tooltip = paste(img(src="http://tippy.john-coene.com/logo.png")),
          placement = "right",
          arrow = TRUE,
          theme = "light"
    )
  ),
  server = function(input, output) {}
)
```

**Comment by markgrujic** [comment]
Great! The size is now working perfectly. Super minor point, but the tooltip margin doesn't encompass the content.

![image](https://user-images.githubusercontent.com/39284163/49256800-4ed14c80-f484-11e8-994c-0487592ff44e.png)

Thanks for the updates

**Comment by rdatasculptor** [comment]
If I understand correctly there is no way to make the tooltip bigger? Sometimes, with too much text the box stops growing and the text doesn't fit. Is there a solution for this...?

**Comment by JohnCoene** [comment]
This is now doable on the latest version, sorry it took so long to fix.

```r
library(shiny)
library(tippy)

shinyApp(
  ui = fluidPage(
    tippy("<b>Text</b>",
          allowHTML = T,
          interactive = T,
          content = paste(
            img(
              src="http://tippy.john-coene.com/logo.png",
              height="200px", 
            )
          ),
          placement = "right",
          arrow = T,
          maxWidth = 600 # this doesn't appear to do anything
    )
  ),
  server = function(input, output) {}
)
```
