### ISSUE TITLE
How to make tippy() tooltip popup bigger?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/tippy#11]
If I  understand correctly there is no way to control the height and width of the `tippy()` pop up box. Am I right or did I miss something?

Many thanks in advance!

**Comment by JohnCoene** [comment]
Not directly I believe, but since it supports HTML one can use any CSS.

```r
tippy("<strong>Works with html!</strong>", 
  tooltip = "<div style='height:100px;'>I'm the tooltip!</div>",
)
```

Alternatively you could create a utility function and a class.

```r
tippy_square <- function(text, content, ...){
  content <- sprintf("<div class='tp'>%s</div>", content)
  tippy(text, content, ...)
}

htmltools::browsable(
  htmltools::tagList(
    htmltools::tags$style(
      ".tp{
        height:200px;
        width:200px;
        text-align: center;
      }"
    ),
    tippy_square("Hover me", "Tooltip")
  )
)
```

**Comment by rdatasculptor** [comment]
yesss. Nice, good working solutions! thanks again John :)

**Comment by rdatasculptor** [comment]
I still run into a problem when there is a lot of text. The black background doesn't seem endless. When you add enought lines in the tooltip, you will see it seem actually a circle. Any ideas about how to make the black background bigger?
