### ISSUE TITLE
How to make tippy popup box bigger?

### ISSUE THREAD

**Issue by mj-at-qb** [JohnCoene/tippy#13]
As mentioned [here,](https://github.com/JohnCoene/tippy/issues/11#issuecomment-808802968) when there are enough lines of text, the popup box will not fit around them all and the text overflows. Additionally, when the popup box reaches it max height/width, 2 of the corners are rounded. My main question: Is there a way to force the popup box to contain all text? Side question: is it possible to overwrite the rounded corners? 

Thanks in advance for any help.

**Comment by JohnCoene** [comment]
With the latest version (from Github) you can use `maxWidth`.

```r
library(shiny)
library(tippy)

ui <- fluidPage(
  useTippy(),
  p("Another tooltip", id = "tip"),
  tippyThis(
    "tip",
    maxWidth = 800, # max width of tooltip in pixels
    "This is indeed an extremely long tooltip with way, way too much text but should display on a single line."
  )
)

server <- function(input, output) {}

shinyApp(ui, server)
```

Sorry for the late response.

**Comment by mj-at-qb** [comment]
No worries on the delay. Thanks for the help!
