### ISSUE TITLE
tippy_theme function?

### ISSUE THREAD

**Issue by mpadge** [JohnCoene/tippy#3]
Great package @JohnCoene! Thanks for immediately beautifying my world! This may already be possible, but I at least couldn't readily see how. Is there some kind of `tippy_theme()` function to set a bunch of default parameters so subsequent calls within same R session can then be just `tippy("text", tooltip = "tip")` minus the other distracting guff? Obvious and direct analogy to `ggplot2::theme_update()`. This functionality - if not currently possible - ought to be pretty easy to incorporate, and would at least for me be quite useful.

**Comment by JohnCoene** [comment]
Thanks!

Good idea, I'll implement that function.

**Comment by JohnCoene** [comment]
At long last, after 2 years+, I've finally pushed a this feature.

I do apologise it took so long.

```r
library(shiny)
library(tippy)

tippy_global_theme("light")

ui <- fluidPage(
  useTippy(),
  p("Another tooltip", id = "tip"),
  tippyThis(
    "tip",
    maxWidth = 800, # max width of tooltip in pixels
    "This is indeed an extremely long tooltip with way, way too much text but should display on a single line."
  )
)

server <- function(input, output) {}

shinyApp(ui, server)
```

**Comment by mpadge** [comment]
That's brilliant - nothing like realising you'd completely forgotten about some long-gone request, only for it to be solved and then realise it's still really, really helpful! Thank you!
